# TREAD Configuration for DocMentor

# General Settings
general:
  enabled: true
  version: "1.0.0"
  cache_enabled: true
  cache_size: 1000
  num_workers: 4

# Token Routing Settings
routing:
  threshold: 0.5
  min_tokens_per_layer: 0.3
  medical_term_weight: 1.5
  cache_routing_patterns: true
  dynamic_routing: true

# Medical Processing
medical:
  enhance_terminology: true
  preserve_context: true
  priority_terms:
    - diagnosis
    - treatment
    - symptoms
    - prognosis
    - dosage
    - contraindications

# Performance Optimization
performance:
  batch_size: 32
  max_sequence_length: 512
  use_fp16: true
  optimize_memory: true
  gpu_acceleration: auto

# Logging and Monitoring
logging:
  enabled: true
  level: "INFO"
  performance_metrics: true
  memory_tracking: true
  save_statistics: true
  log_directory: "logs/tread/"

# Integration Settings
integration:
  pdf_processor_enabled: true
  vector_store_optimization: true
  distilbert_optimization: true
  streamlit_cache_support: true